require("./src/styles/global.css")
require("./src/styles/search.css")
require("./src/styles/home.css")
require("./src/styles/tablet.css")
require("./src/styles/mobile.css")
require("./src/styles/tiny.css")
require("./src/styles/prism-a11y-dark.css")
require("katex/dist/katex.min.css")