export const articles = [
  {
    style: `box1`,
    title: `Neuron model`,
    subtitle: `The idea is simple: make all neurons physical objects like balls`,
    url: `/make/neuron-model`,
    excerpt: ``,
    readMore: ``,
    imgSrc: `neuron-model-3.jpg`,
    imgAlt: null,
  },
  {
    style: `box2`,
    title: `Neuron model`,
    subtitle: `The idea is simple: make all neurons physical objects like balls`,
    url: `/make/neuron-model`,
    excerpt: ``,
    readMore: ``,
    imgSrc: null,
    imgAlt: null,
  },
  {
    style: `box3`,
    title: `Neuron model`,
    subtitle: `The idea is simple: make all neurons physical objects like balls`,
    url: `/make/neuron-model`,
    excerpt: ``,
    readMore: ``,
    imgSrc: null,
    imgAlt: null,
  },
  {
    style: `box4`,
    title: `Neuron model`,
    subtitle: `The idea is simple: make all neurons physical objects like balls`,
    url: `/make/neuron-model`,
    excerpt: ``,
    readMore: ``,
    imgSrc: null,
    imgAlt: null,
  },
  {
    style: `box5`,
    title: `Neuron model`,
    subtitle: `The idea is simple: make all neurons physical objects like balls`,
    url: `/make/neuron-model`,
    excerpt: ``,
    readMore: ``,
    imgSrc: null,
    imgAlt: null,
  },
  {
    style: `box6`,
    title: `Neuron model`,
    subtitle: `The idea is simple: make all neurons physical objects like balls`,
    url: `/make/neuron-model`,
    excerpt: ``,
    readMore: ``,
    imgSrc: null,
    imgAlt: null,
  },
];