export const articles = [
  {
    style: `box1`,
    title: `Logic model of the world`,
    subtitle: `The idea is simple:`,
    url: `/science/logic-model-of-the-world`,
    excerpt: `
    <p>make all neurons physical objects like balls</p>
    <p>Find a working example with a small neural network and make all neurons physical, 
    and train it much faster because all neuron is independent. 
    Each neuron is a FPGA that just immediately reacts on incoming signal, adjusts its weights and carry on.</p>`,
    readMore: ``,
    imgSrc: `/images/home/logic-model-of-the-world.png`,
    imgAlt: `generated by DALL-E`,
  },
  {
    style: `box2`,
    title: `Developmental Psychology studies`,
    subtitle: ``,
    url: `/science/developmental-psychology-stydies`,
    excerpt: `<p>So here is the story how tiny plan stayed with me for 2 month.</p>
    <p>Basic install of elasticsearch with only system metrics takes 2.3GB of memory.</p>
    <p>I'm not saying that it created a nice dashboard, it could be better. But I like that the system is very modular, 
    so maybe I should take a look at the sources and strip it.</p>`,
    readMore: `Can Java VM be tiny?`,
    imgSrc: `/images/home/sensor-dashboard.jpg`,
    imgAlt: null,
  },
  {
    style: `box3`,
    title: `How to use PyTorch`,
    subtitle: `Explain like I am 5`,
    url: `/science/explain-like-i-am-5-how-to-use-pytorch`,
    excerpt: ``,
    readMore: ``,
    imgSrc: null,
    imgAlt: null,
  },
  {
    style: `box4`,
    title: `Prusa Mini Original`,
    subtitle: `Assembly`,
    url: `/make/3d-printer-dilemma`,
    excerpt: `<p>What’s funny that one night I had a dream
      where I followed a step by step tutorial similar to what I used in the last 3 evenings. 
      But in the dream that tutorial was explaining how to hide a treasure
      and put future treasure hunters on a false track</p>
    `,
    readMore: `I successfully finished the assembly of my first 3d printer`,
    imgSrc: `/images/home/prusa-original-mini-assembly-1.jpg`,
    imgAlt: null,
  },
  {
    style: `box5`,
    title: `Everything you need to know`,
    subtitle: `about Jupyter Notebook`,
    url: `/science/everything-you-need-to-know-about-jupyter-notebook`,
    excerpt: `<p>It would be strange to learn Machine Learning and never use Jupyter notebooks.</p>`,
    readMore: `Data scientist LOVE Jupyter notebooks.`,
    imgSrc: null,
    imgAlt: null,
  },
  {
    style: `box6`,
    title: `Geek tools`,
    subtitle: ``,
    url: `/blog/geek-tools`,
    excerpt: `<p>And I'm thinking that the proper weather app should include more!</p>`,
    readMore: ``,
    imgSrc: null,
    imgAlt: null,
  },
];