import React from "react"
import { Link } from "gatsby"
import Layout from "../components/layout"

const IdeasPage = ({ pageContext }) => (
  <Layout
    title="Ideas"
    section="ideas"
    crumbs={pageContext.breadcrumb.crumbs}
    languageName="Switch to russian version"
    anotherLanguageLink="/ru/ideas"
    buttonText="Try free Idea Generator"
    buttonLink="/idea-generator/"
    secondButtonText="Creative ideas for app development"
    secondButtonLink="/creative-ideas-for-app-development/"
    bannerParagraph={[
      <h1>Ideas for new projects?</h1>,
      <p>
      So you want to make a great application.
      It is easy. Get an idea here. This is the first step and it is very important.
      </p>
    ]}
  >
    <h2>By category</h2>

    <ul>
      <li><Link to="/ideas/games/">Games</Link></li>
      <li><Link to="/ideas/diy/">DIY</Link></li>
      <li><Link to="/ideas/mobile-app/">Mobile app</Link></li>
      <li><Link to="/ideas/web-app/">Web app</Link></li>
    </ul>

    <h2>Ideas for your next application</h2>
    <ul>
      <li><Link to="/creative-ideas-for-app-development/">Creative ideas for app development</Link></li>
      <li><Link to="/innovative-ideas-for-app-development/">Innovative ideas for app development</Link></li>
      <li><Link to="/ideas-for-app-development/">All of the above</Link></li>
      <li>Weird ones:
        <ul>
          <li>If finding a ship crew is not a problem, then what do I need to make a sailing ship? Wood, a team of woodworkers and a suitable shipyard. Right? How long do you think it takes to make one?</li>
          <li>App that recognizes simple components and reads labels on chips from your phone camera stream and searches for datasheets.</li>
          <li>If I’m not mistaken MTG has something unique about its balance, that even randomly generated cards wouldn’t break it. Let’s make an AI that generates completely new board game from user short sentences (using a LLM (like GPT-3), fine tune it with Magic the Gathering card texts to generate the cards. To do the image, use another model for image generation like wombo)</li>
          <li>"the software engineering urge to get up, quit your job, run away to a ranch and open a farm while living a wholesome lifestyle surrounded by chickens and leaves". I believe software engineers will miss technologies sooner or later. With this idea in mind I propose special digital farms where every perch and stall has monitoring sensor, and big data helps to grow the best crop despite any weather conditions</li>
          <li>Find broken phones for recycling purposes. Salvage only cameras from them. Combine together as many cameras as possible to make pictures with incredible resolution</li>
          <li>Augmented reality program that reconstructs buildings and landscape of the old city deleting modern objects and restoring ruined ones based on camera view</li>
          <li>Augmented reality kitchen. Helps you cook, orders required food from the store</li>
          <li>Website with fake news and real ones mixed together. Users can vote and guess if it's true or not. Fakes are generated by AI system like GPT-2. Real news chosen specifically that you would normally dub them as fake.</li>
          <li>Improve windmill efficiency by changing its design and the form of blades with genetic algorithm</li>
          <li>Tool that takes photos from an Instagram account, passes it through AI tool to enlarge x4 times, then intellectually crops it to desired desktop resolution and every 5 minutes replaces the background with another random picture</li>
          <li>Add Google drive support to open source file manager</li>
        </ul>

      </li>
    </ul>

    <p>Checkout section <a href="/projects">"Projects"</a> to find out my passions.</p>
    <h2>Idea generator</h2>

    <p>
      <a href="/idea-generator/">
        <button className="action-button">Try it</button>
      </a>
    </p>

    <p>
    I see how you feel. You came here bored with new trending technologies.
    They announce new framework every day. They release new programming language every Thursday <sup>[citation needed]</sup>.
    You want to try it all. You want to understand it very well and be the voice of StackOverflow answers, not just a regular reader.
    </p>

    <p>
    So you want to make a great application. It is easy. All you need is these three things.
    </p>

    <div className="cards">
      <div className="card">
        <img src="/card_idea.png" alt="Idea" width="100px" />
        <div className="card-container">
          <h3>Idea</h3>
          <p>Get an idea here. This is the first step and it is very important.</p>
        </div>
      </div>

      <div className="card">
        <img src="/card_code.png" alt="Code" width="100px" />
        <div className="card-container">
          <h3>Code</h3>
          <p>Write source code that fits to your idea. Any language. Any license.</p>
        </div>
      </div>

      <div className="card">
        <img src="/card_art.png" alt="Art" width="100px" />
        <div className="card-container">
          <h3>Art</h3>
          <p>Add colors and pictures. Find good art. I have <a href="/ideas/where-free-art">a list</a> where to look for it.</p>
        </div>
      </div>

    </div>

    <div>
      <p>
      Here it is. Every night you spend few hours before going to bed.
      And depending how lucky you are, you may finish your project and do not become mad before your first release.
      </p>

      
      
      <hr/>
      <small>
      <div>Icons made by <a href="https://www.flaticon.com/authors/wanicon" title="wanicon">wanicon</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
      <div>Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
      </small>

    </div>
  </Layout>
)

export default IdeasPage
