name: Deploy Website

on:
  push:
    branches: [ gatsby ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Gatsby Publish
        uses: enriikke/gatsby-gh-pages-action@v2.2.1
        with:
          # A personal access token needed to push your site after it has been built.
          access-token: ${{ secrets.ACCESS_TOKEN }}
          # The commit message used for pushing changes to the deploy branch.
          commit-message: "Deployed by GitHub Actions"
          # The name under which the deploy commit is pushed to the deploy branch.
          git-config-name: "Nikolay Neupokoev"
          # The email adress under which the deploy commit is pushed to the deploy branch.
          git-config-email: "neupokoev.n@gmail.com"
        env:
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID}}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY}}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
